# 14.1 Filtering Based on String

In [1]:
import pandas as pd

emp_data = {
    'Name': [
        'Niloy', 'Ishrat', 'Pavel', 'Tuhin', 'Sadia', 'Morshed', 'Labiba', 'Harun'
    ],
    'City': [
        'Dhaka', 'new Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Comilla', 'Mymensingh'
    ],
    'Department': [
        'HR', 'IT', 'Finance', 'Sales', 'Marketing', 'Support', 'Admin', 'IT'
    ],
    'Salary': [
        54000, 62000, 50000, 48000, 56000, 51000, 53000, 60000
    ]
}

df = pd.DataFrame(emp_data)
print(df)

      Name            City Department  Salary
0    Niloy           Dhaka         HR   54000
1   Ishrat  new Chittagong         IT   62000
2    Pavel          Khulna    Finance   50000
3    Tuhin        Rajshahi      Sales   48000
4    Sadia          Sylhet  Marketing   56000
5  Morshed         Barisal    Support   51000
6   Labiba         Comilla      Admin   53000
7    Harun      Mymensingh         IT   60000

In [2]:
#filtering city name with n
df.loc[df['City'].str.contains("N", case = False)]

     Name            City Department  Salary
1  Ishrat  new Chittagong         IT   62000
2   Pavel          Khulna    Finance   50000
7   Harun      Mymensingh         IT   60000

In [3]:
#filtering starts with new
df.loc[df['City'].str.contains(r"^new")]

     Name            City Department  Salary
1  Ishrat  new Chittagong         IT   62000

In [4]:
#Ends with a
df.loc[df['City'].str.contains(r"a$")]

     Name     City Department  Salary
0   Niloy    Dhaka         HR   54000
2   Pavel   Khulna    Finance   50000
6  Labiba  Comilla      Admin   53000

In [5]:
# name starts with a vowel
df.loc[df['Name'].str.contains(r"^[AEIOU]", case = False)]

     Name            City Department  Salary
1  Ishrat  new Chittagong         IT   62000

In [6]:
#City contains c | d
df.loc[df['City'].str.contains(r"c|d", case = False)]

     Name            City Department  Salary
0   Niloy           Dhaka         HR   54000
1  Ishrat  new Chittagong         IT   62000
6  Labiba         Comilla      Admin   53000

# 14.2 Adding new Column and Saving the File

In [7]:
df = pd.read_csv('student_marks.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Adding a column with a constant value
df['Country'] = 'Bangladesh'
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh

In [9]:
df['Total marks'] = df['Data Structure Marks'] + df['Algorithm Marks'] + df['Python Marks']
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN

In [10]:
#Condition, A+ in DS
import numpy as np
df['A+ in DS'] = np.where(df['Data Structure Marks']>90, 'A+', 'A')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total marks,A+ in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A

In [11]:
#if pass in DS
df['Passed in DS'] = df['Data Structure Marks'] > 70
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total marks,A+ in DS,Passed in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A,False

In [12]:
#First name in separate column
df["First Name"] = df['FullName'].str.split(' ').str[0]
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A,False,NaN

In [13]:
df1 = pd.read_csv('student_marks.csv')
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#Saving internally
df.to_csv('new_data.csv')

# 14.3 Checking Duplicates and Null Values in DF

In [15]:
import pandas as pd

data = {
  "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
  "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
  "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
print(df)

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     85
4    David     Tokyo     95
5      Bob    London     90

In [16]:
# Check if names are unique or not
print(df['Name'].unique())

len(df['Name'].unique())

['Alice' 'Bob' 'Charlie' 'David']

4

In [17]:
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#Unique data structure marks
print(df1['Data Structure Marks'].unique())
print(len(df1['Data Structure Marks'].unique()))
print(df1['Data Structure Marks'].nunique()) #Counts without null
#unique works for series only

[85. 92. 88. 78. nan 75. 80. 81. 72. 89. 86. 94. 90.]
13
12

In [19]:
#nuniques works for entire df
df1.nunique()

StudentID               20
FullName                20
Data Structure Marks    12
Algorithm Marks         12
Python Marks            12
CompletionStatus         3
EnrollmentDate          20
Instructor               3
Location                 5
dtype: int64

In [20]:
#Checking null
df1.isnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,True,True,True,True,True,True,True,True,True

In [21]:
df1['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
20     True
Name: Data Structure Marks, dtype: bool

In [22]:
df1['Data Structure Marks'].notnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
20    False
Name: Data Structure Marks, dtype: bool

In [23]:
#Check if the column has null value
df1['Data Structure Marks'].hasnans

True

In [24]:
df1['StudentID'].hasnans

True

# 14.4 Handling Duplicates Values

In [25]:
import pandas as pd

data = {
  "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
  "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
  "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)
print(df)

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [26]:
#check if duplicated
df.duplicated().sum()

np.int64(1)

In [27]:
#Deketing duplicate
df.drop_duplicates()

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [28]:
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [29]:
#permanent delete

df.drop_duplicates(inplace=True)

In [30]:
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [31]:
#duplicate name based delete
df.drop_duplicates(subset=['Name'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [32]:
#cities
df.drop_duplicates(subset=['City'], keep = 'last')

      Name      City  Score
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

# 14.5 Handling Null Values

In [33]:
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
#Delete full row if any null exist
df1.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [35]:
#Delete a row if all are null
df1.dropna(how='all', inplace=True)
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [36]:
# Conditional
df1.dropna(subset=['Python Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [37]:
df1.dropna(subset=['Python Marks','Algorithm Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [38]:
df1.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [39]:
df = pd.read_csv('student_marks.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
#Change null
df.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,0,0,0.0,0.0,0.0,0,0,0,0

In [41]:
#Works with string
df['FullName'].fillna('unknown')

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20             unknown
Name: FullName, dtype: object

In [42]:
df['Python Marks'].fillna(df['Python Marks'].mean(),inplace = True)
df

C:\Users\User\AppData\Local\Temp\ipykernel_7840\1382189917.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Python Marks'].fillna(df['Python Marks'].mean(),inplace = True)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN

# 14.6 Statistical Functions in Pandas

In [43]:
df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka

In [44]:
#Summetion
df['Data Structure Marks'].sum()

np.float64(1344.0)

In [45]:
#Max and Min
print(df['Data Structure Marks'].min())
print(df['Data Structure Marks'].max())

72.0
94.0

In [46]:
#Mean -> Average
df['Data Structure Marks'].mean()

np.float64(84.0)

In [47]:
#Median 
df['Data Structure Marks'].median()

np.float64(85.5)

In [48]:
#mode-> Heighest frequency numbers
df['Data Structure Marks'].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64

In [49]:
#Standard Deviation
df['Data Structure Marks'].std()

np.float64(6.501281924871945)

In [50]:
#Co-relation metrix
df[['Data Structure Marks', 'Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.776845
Python Marks                      0.776845      1.000000

In [51]:
#Sum in different columns
df[['Data Structure Marks', 'Python Marks']].sum()

Data Structure Marks    1344.0
Python Marks            1799.0
dtype: float64

In [52]:
#Sum in different columns row wise
df[['Data Structure Marks', 'Python Marks']].sum(axis=1)

0     173.000000
1     177.666667
2     173.000000
3     160.000000
4      95.000000
5     153.000000
6     165.666667
7     166.000000
8     148.000000
9     177.000000
10     91.000000
11    172.000000
12    154.000000
13     85.666667
14    170.000000
15    179.666667
16    183.000000
17    173.000000
18     85.666667
19    175.000000
20     85.666667
dtype: float64

In [53]:
#Do sum and keep in a column
df['Total Marks'] = df.iloc[::, 2:5].sum(axis=1)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667

In [54]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  Total Marks
count             16.000000        16.000000     21.000000    21.000000
mean              84.000000        84.000000     85.666667   213.666667
std                6.501282         6.501282      4.512944    73.089215
min               72.000000        72.000000     76.000000    85.666667
25%               79.500000        79.500000     85.000000   220.000000
50%               85.500000        85.500000     85.666667   247.000000
75%               88.250000        88.250000     88.000000   261.000000
max               94.000000        94.000000     95.000000   273.666667

# 14.7 Apply Function in DF

In [55]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667

In [61]:
#Min max scalling, scalled = (x-min)/(max-min)
mn = df['Total Marks'].min()
mx = df['Total Marks'].max()

df['Scaled Marks'] = df['Total Marks'].apply(lambda x : (x-mn)/(mx-mn))

In [62]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.916667
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667,0.978723
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.932624
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.810284
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.049645
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.757092
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667,0.851064
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.858156
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.714539
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.959220
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028369
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.911348
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.762411
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.906028
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667,1.000000
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000,0.996454
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000,0.932624
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000,0.932624
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667,0.000000

In [63]:
#Custom build fuction
def grading_system(marks):
  if marks >=260:
    return 'A+'
  elif marks >= 250:
    return 'A'
  else:

    return 'A-' 

df['Grade']  = df['Total Marks'].apply(grading_system)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.916667,A
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667,0.978723,A+
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.932624,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.810284,A-
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.049645,A-
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.757092,A-
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667,0.851064,A-
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.858156,A-
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.714539,A-
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.959220,A+
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028369,A-
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.911348,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.762411,A-
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,0.000000,A-
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.906028,A
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667,1.000000,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000,0.996454,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000,0.932624,A+
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,0.000000,A-
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000,0.932624,A+
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667,0.000000,A-

In [67]:
def marking_system(df):
  a = df['Data Structure Marks'] * 2
  b = df['Python Marks'] * 3
  c = df['Algorithm Marks'] * 4

  return a+b+c


df['Exceptional Marks'] = df.apply(marking_system,axis=1)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.916667,A,774.0
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667,0.978723,A+,809.0
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.932624,A+,783.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.810284,A-,714.0
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.049645,A-,NaN
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.757092,A-,684.0
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667,0.851064,A-,737.0
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.858156,A-,741.0
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.714539,A-,660.0
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.959220,A+,798.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028369,A-,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.911348,A,771.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.762411,A-,687.0
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,0.000000,A-,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.906028,A,768.0
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667,1.000000,A+,821.0
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000,0.996454,A+,819.0
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000,0.932624,A+,783.0
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,0.000000,A-,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000,0.932624,A+,783.0
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667,0.000000,A-,NaN