# 14.1 Filtering Based on String

In [24]:
import pandas as pd

emp_data = {
    'Name': [
        'Niloy', 'Ishrat', 'Pavel', 'Tuhin', 'Sadia', 'Morshed', 'Labiba', 'Harun'
    ],
    'City': [
        'Dhaka', 'new Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Comilla', 'Mymensingh'
    ],
    'Department': [
        'HR', 'IT', 'Finance', 'Sales', 'Marketing', 'Support', 'Admin', 'IT'
    ],
    'Salary': [
        54000, 62000, 50000, 48000, 56000, 51000, 53000, 60000
    ]
}

df = pd.DataFrame(emp_data)
print(df)

      Name            City Department  Salary
0    Niloy           Dhaka         HR   54000
1   Ishrat  new Chittagong         IT   62000
2    Pavel          Khulna    Finance   50000
3    Tuhin        Rajshahi      Sales   48000
4    Sadia          Sylhet  Marketing   56000
5  Morshed         Barisal    Support   51000
6   Labiba         Comilla      Admin   53000
7    Harun      Mymensingh         IT   60000

In [25]:
#filtering city name with n
df.loc[df['City'].str.contains("N", case = False)]

     Name            City Department  Salary
1  Ishrat  new Chittagong         IT   62000
2   Pavel          Khulna    Finance   50000
7   Harun      Mymensingh         IT   60000

In [26]:
#filtering starts with new
df.loc[df['City'].str.contains(r"^new")]

     Name            City Department  Salary
1  Ishrat  new Chittagong         IT   62000

In [27]:
#Ends with a
df.loc[df['City'].str.contains(r"a$")]

     Name     City Department  Salary
0   Niloy    Dhaka         HR   54000
2   Pavel   Khulna    Finance   50000
6  Labiba  Comilla      Admin   53000

In [30]:
# name starts with a vowel
df.loc[df['Name'].str.contains(r"^[AEIOU]", case = False)]

     Name            City Department  Salary
1  Ishrat  new Chittagong         IT   62000

In [32]:
#City contains c | d
df.loc[df['City'].str.contains(r"c|d", case = False)]

     Name            City Department  Salary
0   Niloy           Dhaka         HR   54000
1  Ishrat  new Chittagong         IT   62000
6  Labiba         Comilla      Admin   53000